### ISSUE TITLE
Can't debug forking applications

### ISSUE THREAD

**Issue by 10110111** [GLSL-Debugger/GLSL-Debugger#45]
If a debuggee tries to fork(2), GLSL-Debugger thinks that it exited, although I think it's the child which had. Here's the console output of my Qt4 application when KDE4 Oxygen style is in use:

```
2016-06-26 18:42:39 [INFO ]::glsldb.cpp:main()::380: Application startup.
2016-06-26 18:42:39 [INFO ]::FunctionsMap.cpp:initialize()::21: 2624 registered GL-Functions
Absolute path to debugger executable is: /home/ruslan/src/GLSL-Debugger/build/bin/glsldb
Path to debug library is: /home/ruslan/src/GLSL-Debugger/build/bin/../lib/libglsldebug.so
Path to debug functions is: /home/ruslan/src/GLSL-Debugger/build/bin/../lib/plugins
Path to libdlsym is: /home/ruslan/src/GLSL-Debugger/build/bin/../lib/libdlsym.so
2016-06-26 18:42:39 [INFO ]::mainWindow.cpp:setRunLevel()::3196: new level: 1 
env dbglib: "/home/ruslan/src/GLSL-Debugger/build/bin/../lib/libglsldebug.so"
env shmid: "523370523"
env dbgfctns: "/home/ruslan/src/GLSL-Debugger/build/bin/../lib/plugins"
libdlsym: "/home/ruslan/src/GLSL-Debugger/build/bin/../lib/libdlsym.so"
env dbglvl: "6"
env dbglogdir: ""
debuggee executes build/diffraction-patterns
debuggee process pid: 17677
waiting for debuggee to respond...
checking debuggee status...
debuggee process was stopped by SIGTRAP 5
sending continue
checking debuggee status...
debuggee process was stopped by signal 17: Child exited
2016-06-26 18:42:41 [INFO ]::mainWindow.cpp:setRunLevel()::3196: new level: 1 
```

Here's what I have when I catch `fork` syscall in GDB:
```
(gdb) catch fork
Catchpoint 1 (fork)
(gdb) r
Starting program: /home/ruslan/myprogs/diffraction-patterns/build/diffraction-patterns 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/libthread_db.so.1".
Qt: gdb: -nograb added to command-line options.
         Use the -dograb option to enforce grabbing.

Catchpoint 1 (forked process 20127), 0xffffe430 in __kernel_vsyscall ()
(gdb) bt
#0  0xffffe430 in __kernel_vsyscall ()
#1  0xf6a3709c in __libc_fork () at ../nptl/sysdeps/unix/sysv/linux/i386/../fork.c:131
#2  0xf6cea4d5 in __fork () at ../nptl/sysdeps/unix/sysv/linux/pt-fork.c:26
#3  0xf108946c in _read_subprocess_line_argv () from /usr/lib/libdbus-1.so.3
#4  0xf10899a8 in _dbus_get_autolaunch_address () from /usr/lib/libdbus-1.so.3
#5  0xf107b880 in _dbus_transport_new_for_autolaunch () from /usr/lib/libdbus-1.so.3
#6  0xf107b936 in _dbus_transport_open_autolaunch () from /usr/lib/libdbus-1.so.3
#7  0xf107ba30 in _dbus_transport_open () from /usr/lib/libdbus-1.so.3
#8  0xf105e09b in connection_try_from_address_entry () from /usr/lib/libdbus-1.so.3
#9  0xf105e218 in _dbus_connection_open_internal () from /usr/lib/libdbus-1.so.3
#10 0xf105efb7 in dbus_connection_open_private () from /usr/lib/libdbus-1.so.3
#11 0xf105b378 in internal_bus_get () from /usr/lib/libdbus-1.so.3
#12 0xf105b492 in dbus_bus_get_private () from /usr/lib/libdbus-1.so.3
#13 0xf15c2b5c in q_dbus_bus_get_private (type=DBUS_BUS_SESSION, error=0xffffce00) at qdbus_symbols_p.h:101
#14 0xf15c34cb in QDBusConnection::connectToBus (type=QDBusConnection::SessionBus, name="qt_default_session_bus") at qdbusconnection.cpp:353
#15 0xf15c658b in QDBusDefaultConnection::QDBusDefaultConnection (this=0x8185778, type=QDBusConnection::SessionBus, name=0xf1618590 "qt_default_session_bus") at qdbusconnection.cpp:1108
#16 0xf15c55ea in _q_sessionBus () at qdbusconnection.cpp:1124
#17 0xf15c5826 in QDBusConnection::sessionBus () at qdbusconnection.cpp:1131
#18 0xf216bc17 in Oxygen::Style::Style (this=0x8160208) at /home/ruslan/src/kde4/4.14/kde-workspace-4.11.14/kstyles/oxygen/oxygenstyle.cpp:190
#19 0xf217c1c8 in Oxygen::StylePlugin::create (this=0x815c540, key="oxygen") at /home/ruslan/src/kde4/4.14/kde-workspace-4.11.14/kstyles/oxygen/oxygenstyle.cpp:127
#20 0xf764ba2c in QStyleFactory::create (key="Oxygen") at styles/qstylefactory.cpp:193
#21 0xf72c1bc3 in QApplication::style () at kernel/qapplication.cpp:1469
#22 0xf72c0b1d in QApplicationPrivate::initialize (this=0x80aa788) at kernel/qapplication.cpp:991
#23 0xf72c05b3 in QApplicationPrivate::construct (this=0x80aa788, dpy=0x0, visual=0, cmap=0) at kernel/qapplication.cpp:843
#24 0xf72c012f in QApplication::QApplication (this=0xffffd26c, argc=@0xffffd340: 1, argv=0xffffd3d4, _internal=17041415) at kernel/qapplication.cpp:741
#25 0x08053bb4 in main (argc=1, argv=0xffffd3d4) at ../main.cpp:30
```

My current workaround is to run my app with `-style plastique` option, but of course if the application itself needed to fork, GLSL-Debugger would be useless for it in its current state.

**Comment by napcode** [comment]
Thank you for your report. Closing it since it is the same issue as described in #15

**Comment by 10110111** [comment]
Well I see that it's the same, but in bug #15 the problem is with following the child, while here the problem is that the child has died but not the parent. The problem occurs even in this simple case:

```
#include <unistd.h>
#include <stdlib.h>

int main()
{
    if(!fork()) exit(55);
    for(volatile int x=0;;++x);
}
```

It seems to me that a debugger should at least always keep its eye on the original debuggee if it doesn't support following the children.
