### ISSUE TITLE
Cannot debug program with Python interpreter

### ISSUE THREAD

**Issue by cedricp** [GLSL-Debugger/GLSL-Debugger#62]
Hi,

I'm trying to debug a Python program with this tool, but it seems there's a problem on Linux when it tries to load a module, I get this error : 
checking debuggee status...
```
Traceback (most recent call last):
  File "/home/cedric/Desktop/series.py", line 1, in <module>
    import math
SystemError: dynamic module not initialized properly
```

I think it's a dynamic linker issue, but I don't know what could be missing... Any idea ?
Thank you

**Comment by o4dev** [comment]
This no logger works even with fix. The process just terminates straight away.

```
debuggee process pid: 28059
waiting for debuggee to respond...
checking debuggee status...
debuggee process was stopped by SIGTRAP 5
sending continue
checking debuggee status...
debuggee process was stopped by signal 17: Child exited
2020-12-12 21:06:19 [INFO ]::mainWindow.cpp:setRunLevel()::3195: new level: 1 
```

**Comment by Rayzeq** [comment]
I can confirm that no longer work. Here's the full logs:
```
2021-06-01 16:05:30 [INFO ]::glsldb.cpp:main()::374: Application startup.
2021-06-01 16:05:30 [INFO ]::FunctionsMap.cpp:initialize()::21: 2624 registered GL-Functions
Absolute path to debugger executable is: /home/zacharie/Téléchargements/GLSL-Debugger/Build/bin/glsldb
Path to debug library is: /home/zacharie/Téléchargements/GLSL-Debugger/Build/bin/../lib/libglsldebug.so
Path to debug functions is: /home/zacharie/Téléchargements/GLSL-Debugger/Build/bin/../lib/plugins
Path to libdlsym is: /home/zacharie/Téléchargements/GLSL-Debugger/Build/bin/../lib/libdlsym.so
2021-06-01 16:05:30 [INFO ]::mainWindow.cpp:setRunLevel()::3196: new level: 0 
2021-06-01 16:05:33 [TRACE]::mainWindow.cpp:killProgram()::248: Killing debugee
killing debuggee: forced2021-06-01 16:05:33 [INFO ]::mainWindow.cpp:setRunLevel()::3196: new level: 1 
2021-06-01 16:05:34 [TRACE]::mainWindow.cpp:on_tbExecute_clicked()::586: Executing
env dbglib: "/home/zacharie/Téléchargements/GLSL-Debugger/Build/bin/../lib/libglsldebug.so"
env shmid: "1802264"
env dbgfctns: "/home/zacharie/Téléchargements/GLSL-Debugger/Build/bin/../lib/plugins"
libdlsym: "/home/zacharie/Téléchargements/GLSL-Debugger/Build/bin/../lib/libdlsym.so"
env dbglvl: "5"
env dbglogdir: ""
debuggee executes main.py
debuggee process pid: 206935
waiting for debuggee to respond...
checking debuggee status...
debuggee process was stopped by SIGTRAP 5
sending continue
checking debuggee status...
debuggee process was stopped by SIGTRAP 5
2021-06-01 16:05:34 [INFO ]::mainWindow.cpp:setRunLevel()::3196: new level: 2 
2021-06-01 16:05:34 [INFO ]::mainWindow.cpp:setRunLevel()::3196: new level: 3 
2021-06-01 16:05:36 [INFO ]::mainWindow.cpp:setRunLevel()::3196: new level: 5 
send: DBG_CALL_ORIGFUNCTION
checking debuggee status...
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    from world import World, Pixel
  File "/media/Stockage/Programmation/Python/PixelPhysic/world.py", line 5, in <module>
    import numpy as np
  File "/home/zacharie/.local/lib/python3.8/site-packages/numpy/__init__.py", line 145, in <module>
    from . import core
  File "/home/zacharie/.local/lib/python3.8/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/home/zacharie/.local/lib/python3.8/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/home/zacharie/.local/lib/python3.8/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
SystemError: initialization of _multiarray_umath failed without raising an exception
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 55, in apport_excepthook
    import apt_pkg
SystemError: initialization of apt_pkg failed without raising an exception

Original exception was:
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    from world import World, Pixel
  File "/media/Stockage/Programmation/Python/PixelPhysic/world.py", line 5, in <module>
    import numpy as np
  File "/home/zacharie/.local/lib/python3.8/site-packages/numpy/__init__.py", line 145, in <module>
    from . import core
  File "/home/zacharie/.local/lib/python3.8/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/home/zacharie/.local/lib/python3.8/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/home/zacharie/.local/lib/python3.8/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
SystemError: initialization of _multiarray_umath failed without raising an exception
debuggee terminated normally with status 1
2021-06-01 16:05:37 [TRACE]::mainWindow.cpp:killProgram()::248: Killing debugee
killing debuggee: forcedchecking debuggee status...
checking clones: -1 -1
no such debuggee!
2021-06-01 16:05:37 [INFO ]::mainWindow.cpp:setRunLevel()::3196: new level: 1 
2021-06-01 16:05:43 [TRACE]::mainWindow.cpp:killProgram()::248: Killing debugee
killing debuggee: forced2021-06-01 16:05:43 [TRACE]::mainWindow.cpp:~MainWindow()::208: ~MainWindow kill program
2021-06-01 16:05:43 [TRACE]::mainWindow.cpp:killProgram()::248: Killing debugee
killing debuggee: forced2021-06-01 16:05:43 [TRACE]::mainWindow.cpp:~MainWindow()::212: ~MainWindow free pc
~ProgramControl freeShmem()
```
